[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # You can adjust this if needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add any other Netlify-specific configurations here